#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative "setup"

TemporalService.setup

worker = Temporal::Worker.new

worker.register_workflow(Workflows::SyncWorkflow)
worker.register_workflow(Workflows::ScheduleSyncWorkflow)
worker.register_workflow(Workflows::TerminateWorkflow)

# Re-enabled after fixing connection.close issue in DatabaseMiddleware
# The middleware now only calls clear_active_connections! in the ensure block
# The with_connection block handles proper connection checkout/checkin lifecycle
worker.add_workflow_task_middleware(Middlewares::DatabaseMiddleware)

worker.register_activity(Activities::FetchSyncActivity)
worker.register_activity(Activities::CreateSyncRunActivity)
worker.register_activity(Activities::ExtractorActivity)
worker.register_activity(Activities::LoaderActivity)
worker.register_activity(Activities::ReporterActivity)
worker.register_activity(Activities::ScheduleSyncActivity)
worker.register_activity(Activities::TerminateWorkflowActivity)

# TODO: add logging middleware to all workflows and activities

worker.add_workflow_task_middleware(Middlewares::LoggingMiddleware, "MULTIWOVEN")
worker.add_activity_middleware(Middlewares::LoggingMiddleware, "MULTIWOVEN")
worker.add_workflow_middleware(Middlewares::UpdateSyncRunStatusMiddleware)

Utils::HealthChecker.run

worker.start
